package userInterface;

import javax.swing.JOptionPane;

/**
 *
 * @author n10245090
 */
public class addOU extends javax.swing.JFrame {

    /**
     * Creates new form addOU
     */
    public addOU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createOULabel = new javax.swing.JLabel();
        OUNameLabel = new javax.swing.JLabel();
        OUCreditsLabel = new javax.swing.JLabel();
        OUAssetsLabel = new javax.swing.JLabel();
        createOUBtn = new javax.swing.JButton();
        OUNameTextField = new javax.swing.JTextField();
        OUCreditsTextField = new javax.swing.JTextField();
        OUAssetsTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New OU");

        createOULabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        createOULabel.setText("CREATE NEW OU");

        OUNameLabel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        OUNameLabel.setText("Enter name of OU:");

        OUCreditsLabel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        OUCreditsLabel.setText("Enter number of OU credits:");

        OUAssetsLabel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        OUAssetsLabel.setText("Enter number of OU assets:");

        createOUBtn.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        createOUBtn.setText("CREATE");
        createOUBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createOUBtnActionPerformed(evt);
            }
        });

        OUNameTextField.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        OUCreditsTextField.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        OUAssetsTextField.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(128, 128, 128)
                                                .addComponent(createOULabel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(OUCreditsLabel)
                                                        .addComponent(OUNameLabel)
                                                        .addComponent(OUAssetsLabel))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(OUNameTextField)
                                                        .addComponent(OUCreditsTextField)
                                                        .addComponent(OUAssetsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(162, 162, 162)
                                                .addComponent(createOUBtn)))
                                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(createOULabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(OUNameLabel)
                                        .addComponent(OUNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(OUCreditsLabel)
                                        .addComponent(OUCreditsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(OUAssetsLabel)
                                        .addComponent(OUAssetsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(createOUBtn)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createOUBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createOUBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "OU Added");
    }//GEN-LAST:event_createOUBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addOU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addOU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addOU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addOU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addOU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OUAssetsLabel;
    private javax.swing.JTextField OUAssetsTextField;
    private javax.swing.JLabel OUCreditsLabel;
    private javax.swing.JTextField OUCreditsTextField;
    private javax.swing.JLabel OUNameLabel;
    private javax.swing.JTextField OUNameTextField;
    private javax.swing.JButton createOUBtn;
    private javax.swing.JLabel createOULabel;
    // End of variables declaration//GEN-END:variables
}
