package userInterface;


import COMMON.OrganisationUnit;
import COMMON.User;
import Client.ServerConnection;

import javax.swing.JOptionPane;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author n10245090
 */
public class addUser extends javax.swing.JFrame {

    private ServerConnection serverConnection;
    private ArrayList<OrganisationUnit> OrganisationUnits;
    /**
     * Creates new form addUser
     */
    public addUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addUserLabel = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        newUserLabel = new javax.swing.JLabel();
        newpassLabel = new javax.swing.JLabel();
        newUserTextField = new javax.swing.JTextField();
        newPassTextField = new javax.swing.JTextField();
        OUcomboBox = new javax.swing.JComboBox<>();
        adminCheckBox = new javax.swing.JCheckBox();
        userCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New User");

        addUserLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addUserLabel.setText("CREATE NEW USER");

        createBtn.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        createBtn.setText("CREATE");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    createBtnActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        newUserLabel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        newUserLabel.setText("Enter the username:");

        newpassLabel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        newpassLabel.setText("Enter the password:");

        newUserTextField.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        newUserTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserTextFieldActionPerformed(evt);
            }
        });

        newPassTextField.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        //OUcomboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OU 1", "OU 2", "OU 3", "OU 4" }));
        serverConnection = new ServerConnection();
        OrganisationUnits = serverConnection.GetOUs();
        for(OrganisationUnit OU : OrganisationUnits) {
            OUcomboBox.addItem(OU.orgName());
        }

        adminCheckBox.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        adminCheckBox.setText("Admin");

        userCheckBox.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        userCheckBox.setText("User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(newpassLabel)
                                        .addComponent(newUserLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(newUserTextField)
                                        .addComponent(newPassTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(adminCheckBox)
                                        .addComponent(userCheckBox))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(148, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(OUcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(189, 189, 189))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(createBtn)
                                                .addGap(181, 181, 181))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(addUserLabel)
                                                .addGap(146, 146, 146))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(addUserLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newUserLabel)
                                        .addComponent(newUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adminCheckBox))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newpassLabel)
                                        .addComponent(newPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(userCheckBox))
                                .addGap(18, 18, 18)
                                .addComponent(OUcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(createBtn)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newUserTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newUserTextFieldActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        serverConnection = new ServerConnection();
        String Username = newUserTextField.getText();
        OrganisationUnit SelectedOrgUnit = null;
        String Password = newPassTextField.getText();
        String OUName = (String) OUcomboBox.getSelectedItem();
        for(OrganisationUnit OU : OrganisationUnits) {
            if(OU.orgName().equals(OUName)) {
                SelectedOrgUnit = OU;
            }
        }
        serverConnection.AddUser(new User(Username,Password,SelectedOrgUnit));
        JOptionPane.showMessageDialog(this, "User Added");
    }//GEN-LAST:event_createBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> OUcomboBox;
    private javax.swing.JLabel addUserLabel;
    private javax.swing.JCheckBox adminCheckBox;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField newPassTextField;
    private javax.swing.JLabel newUserLabel;
    private javax.swing.JTextField newUserTextField;
    private javax.swing.JLabel newpassLabel;
    private javax.swing.JCheckBox userCheckBox;
    // End of variables declaration//GEN-END:variables
}