package userInterface;

import COMMON.Asset;
import COMMON.OrganisationUnit;
import Client.ServerConnection;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author n10245090
 */
public class editOU extends javax.swing.JFrame {
    private  ArrayList<OrganisationUnit> OrgUnits;
    private ArrayList<Asset> Assets;
    /**
     * Creates new form editOU
     */
    public editOU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        OrgUnits = new ArrayList<>();
        ServerConnection DataConnection = new ServerConnection();
        OrgUnits = DataConnection.GetOUs();
        OrganisationUnit SelectedOU = null;
        editOUTitleLabel = new javax.swing.JLabel();
        editOULabel = new javax.swing.JLabel();
        editOUComboBox = new javax.swing.JComboBox<>();
        newCreditsLabel = new javax.swing.JLabel();
        newCreditsTextField = new javax.swing.JTextField();
        assetTypeLabel = new javax.swing.JLabel();
        assetTypeComboBox = new javax.swing.JComboBox<>();
        newAssetsLabel = new javax.swing.JLabel();
        newAssetsTextField = new javax.swing.JTextField();
        editBtn = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        editOUTitleLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        editOUTitleLabel.setText("EDIT OU");

        editOULabel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        editOULabel.setText("Select OU to edit:");

        editOUComboBox.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        //editOUComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OU 1", "OU 2", "OU 3", "OU 4" }));
        for(OrganisationUnit OU : OrgUnits) {
            editOUComboBox.addItem(OU.orgName());
        }
        editOUComboBox.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                NewOUSelected(e);
            }
        });
        newCreditsLabel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        newCreditsLabel.setText("Enter new credits for OU:");

        newCreditsTextField.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        assetTypeLabel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        assetTypeLabel.setText("Select asset type for OU:");

        assetTypeComboBox.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        //assetTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));


        newAssetsLabel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        newAssetsLabel.setText("Enter new assets for OU:");

        newAssetsTextField.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        newAssetsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAssetsTextFieldActionPerformed(evt);
            }
        });

        editBtn.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        editBtn.setText("EDIT");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(159, 159, 159)
                                                .addComponent(editOUTitleLabel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(newCreditsLabel)
                                                        .addComponent(editOULabel)
                                                        .addComponent(assetTypeLabel)
                                                        .addComponent(newAssetsLabel))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(editOUComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(newCreditsTextField)
                                                        .addComponent(assetTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(newAssetsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(editBtn)
                                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(editOUTitleLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(editOULabel)
                                        .addComponent(editOUComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newCreditsLabel)
                                        .addComponent(newCreditsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(assetTypeLabel)
                                        .addComponent(assetTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newAssetsLabel)
                                        .addComponent(newAssetsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(editBtn)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewOUSelected(ActionEvent e) {
        ServerConnection DataSource = new ServerConnection();
        Assets = DataSource.GetAllAssets_OU( (String) editOUComboBox.getSelectedItem());
        for(Asset asset : Assets) {
            assetTypeComboBox.addItem(asset.GetName());
        }
    }

    private void newAssetsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAssetsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newAssetsTextFieldActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        OrganisationUnit SelectedOrgUnit = null;
        Asset SelectAsset = null;
        ServerConnection Datasource = new ServerConnection();
        if(!newCreditsTextField.getText().isEmpty()) {
            for (OrganisationUnit OU : OrgUnits) {
                if (OU.orgName().equals(editOUComboBox.getSelectedItem())) {
                    SelectedOrgUnit = OU;
                }
            }
            Datasource.EditOU(SelectedOrgUnit, Double.parseDouble(newCreditsTextField.getText()));
        }
        if(!newAssetsTextField.getText().isEmpty()) {
            for(Asset asset : Assets) {
                if(asset.GetName().equals(assetTypeComboBox.getSelectedItem())) {
                    SelectAsset = asset;
                }
            }
            Datasource.EditAsset(SelectAsset,(String) newAssetsTextField.getText());
        }
        JOptionPane.showMessageDialog(this, "OU Edited");
    }//GEN-LAST:event_editBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editOU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editOU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editOU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editOU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editOU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> assetTypeComboBox;
    private javax.swing.JLabel assetTypeLabel;
    private javax.swing.JButton editBtn;
    private javax.swing.JComboBox<String> editOUComboBox;
    private javax.swing.JLabel editOULabel;
    private javax.swing.JLabel editOUTitleLabel;
    private javax.swing.JLabel newAssetsLabel;
    private javax.swing.JTextField newAssetsTextField;
    private javax.swing.JLabel newCreditsLabel;
    private javax.swing.JTextField newCreditsTextField;
    // End of variables declaration//GEN-END:variables
}
