package userInterface;

public class mainPage extends javax.swing.JFrame {

    /**
     * Creates new form mainPage
     */
    public mainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        availableOrdersPanel = new javax.swing.JPanel();
        avaialbleTabbedPane = new javax.swing.JTabbedPane();
        avBuyPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buyBtn = new javax.swing.JButton();
        avSellPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        sellBtn = new javax.swing.JButton();
        currentOrdersPanel = new javax.swing.JPanel();
        currentTabbedPane = new javax.swing.JTabbedPane();
        currBuyPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        buyRemoveBtn = new javax.swing.JButton();
        currSellPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        sellRemoveBtn = new javax.swing.JButton();
        createOrdersPanel = new javax.swing.JPanel();
        createLabel = new javax.swing.JLabel();
        buySellComboBox = new javax.swing.JComboBox<>();
        assetTypeComboBox = new javax.swing.JComboBox<>();
        valueLabel = new javax.swing.JLabel();
        qtyLabel = new javax.swing.JLabel();
        valueTextField = new javax.swing.JTextField();
        qtyTextField = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        mainMenuBar = new javax.swing.JMenuBar();
        settingsMenu = new javax.swing.JMenu();
        logoutMenuItem = new javax.swing.JMenuItem();
        staffMenu = new javax.swing.JMenu();
        addUserMenuItem = new javax.swing.JMenuItem();
        addOUMenuItem = new javax.swing.JMenuItem();
        deleteUserMenuItem = new javax.swing.JMenuItem();
        deleteOUMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trading System");
        setPreferredSize(new java.awt.Dimension(1000, 800));

        titleLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("WELCOME TO THE TRADING SOFTWARE");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
                topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(topPanelLayout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(titleLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
                topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(topPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titleLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bottomPanel.setLayout(new java.awt.GridLayout(2, 2));

        availableOrdersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Available Orders", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N

        avaialbleTabbedPane.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "OU", "Asset Name", "Qty", "Price"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        buyBtn.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        buyBtn.setText("BUY");

        javax.swing.GroupLayout avBuyPanelLayout = new javax.swing.GroupLayout(avBuyPanel);
        avBuyPanel.setLayout(avBuyPanelLayout);
        avBuyPanelLayout.setHorizontalGroup(
                avBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                        .addGroup(avBuyPanelLayout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(buyBtn)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        avBuyPanelLayout.setVerticalGroup(
                avBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(avBuyPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buyBtn)
                                .addContainerGap())
        );

        avaialbleTabbedPane.addTab("Available Buy Orders", avBuyPanel);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "OU", "Asset Name", "Qty", "Price"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        sellBtn.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        sellBtn.setText("SELL");

        javax.swing.GroupLayout avSellPanelLayout = new javax.swing.GroupLayout(avSellPanel);
        avSellPanel.setLayout(avSellPanelLayout);
        avSellPanelLayout.setHorizontalGroup(
                avSellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(avSellPanelLayout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(sellBtn)
                                .addContainerGap(196, Short.MAX_VALUE))
        );
        avSellPanelLayout.setVerticalGroup(
                avSellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(avSellPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sellBtn)
                                .addContainerGap())
        );

        avaialbleTabbedPane.addTab("Available Sell Orders", avSellPanel);

        javax.swing.GroupLayout availableOrdersPanelLayout = new javax.swing.GroupLayout(availableOrdersPanel);
        availableOrdersPanel.setLayout(availableOrdersPanelLayout);
        availableOrdersPanelLayout.setHorizontalGroup(
                availableOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(avaialbleTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        availableOrdersPanelLayout.setVerticalGroup(
                availableOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(avaialbleTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        bottomPanel.add(availableOrdersPanel);

        currentOrdersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Current Orders", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N
        currentOrdersPanel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        currentTabbedPane.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "OU", "Asset Name", "Qty", "Price"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setResizable(false);
        }

        buyRemoveBtn.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        buyRemoveBtn.setText("REMOVE");

        javax.swing.GroupLayout currBuyPanelLayout = new javax.swing.GroupLayout(currBuyPanel);
        currBuyPanel.setLayout(currBuyPanelLayout);
        currBuyPanelLayout.setHorizontalGroup(
                currBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                        .addGroup(currBuyPanelLayout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(buyRemoveBtn)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        currBuyPanelLayout.setVerticalGroup(
                currBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(currBuyPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buyRemoveBtn)
                                .addContainerGap())
        );

        currentTabbedPane.addTab("Your Current Buy Orders", currBuyPanel);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "OU", "Asset Name", "Qty", "Price"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        sellRemoveBtn.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        sellRemoveBtn.setText("REMOVE");

        javax.swing.GroupLayout currSellPanelLayout = new javax.swing.GroupLayout(currSellPanel);
        currSellPanel.setLayout(currSellPanelLayout);
        currSellPanelLayout.setHorizontalGroup(
                currSellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                        .addGroup(currSellPanelLayout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(sellRemoveBtn)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        currSellPanelLayout.setVerticalGroup(
                currSellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(currSellPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sellRemoveBtn)
                                .addContainerGap())
        );

        currentTabbedPane.addTab("Your Current Sell Orders", currSellPanel);

        javax.swing.GroupLayout currentOrdersPanelLayout = new javax.swing.GroupLayout(currentOrdersPanel);
        currentOrdersPanel.setLayout(currentOrdersPanelLayout);
        currentOrdersPanelLayout.setHorizontalGroup(
                currentOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(currentTabbedPane)
        );
        currentOrdersPanelLayout.setVerticalGroup(
                currentOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(currentTabbedPane)
        );

        bottomPanel.add(currentOrdersPanel);

        createOrdersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N
        createOrdersPanel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        createLabel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        createLabel.setText("CREATE NEW ORDER");

        buySellComboBox.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        buySellComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BUY", "SELL" }));

        assetTypeComboBox.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        assetTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASSET TYPE 1", "ASSET TYPE 2", "ASSET TYPE 3", "ASSET TYPE 4" }));

        valueLabel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        valueLabel.setText("Enter value of the asset you wish to sell/buy:");

        qtyLabel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        qtyLabel.setText("Enter qty of asset you wish to sell/buy:");

        valueTextField.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        qtyTextField.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        createBtn.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        createBtn.setText("CREATE ORDER");

        javax.swing.GroupLayout createOrdersPanelLayout = new javax.swing.GroupLayout(createOrdersPanel);
        createOrdersPanel.setLayout(createOrdersPanelLayout);
        createOrdersPanelLayout.setHorizontalGroup(
                createOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(createOrdersPanelLayout.createSequentialGroup()
                                .addGroup(createOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(createOrdersPanelLayout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(createOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(valueLabel)
                                                        .addComponent(qtyLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(createOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(valueTextField)
                                                        .addComponent(qtyTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                                        .addGroup(createOrdersPanelLayout.createSequentialGroup()
                                                .addGroup(createOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(createOrdersPanelLayout.createSequentialGroup()
                                                                .addGap(175, 175, 175)
                                                                .addComponent(buySellComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(createOrdersPanelLayout.createSequentialGroup()
                                                                .addGap(150, 150, 150)
                                                                .addGroup(createOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(createLabel)
                                                                        .addComponent(assetTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(createOrdersPanelLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(createBtn)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createOrdersPanelLayout.setVerticalGroup(
                createOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(createOrdersPanelLayout.createSequentialGroup()
                                .addComponent(createLabel)
                                .addGap(14, 14, 14)
                                .addComponent(buySellComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(assetTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(createOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(valueLabel)
                                        .addComponent(valueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(createOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(qtyLabel)
                                        .addComponent(qtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(createBtn)
                                .addGap(0, 58, Short.MAX_VALUE))
        );

        bottomPanel.add(createOrdersPanel);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asset History - Graph", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N
        jPanel10.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 421, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 266, Short.MAX_VALUE)
        );

        bottomPanel.add(jPanel10);

        settingsMenu.setText("Settings");

        logoutMenuItem.setText("logout");
        settingsMenu.add(logoutMenuItem);

        mainMenuBar.add(settingsMenu);

        staffMenu.setText("Staff");

        addUserMenuItem.setText("Add User");
        staffMenu.add(addUserMenuItem);

        addOUMenuItem.setText("Add OU");
        staffMenu.add(addOUMenuItem);

        deleteUserMenuItem.setText("Delete User");
        staffMenu.add(deleteUserMenuItem);

        deleteOUMenuItem.setText("Delete OU");
        staffMenu.add(deleteOUMenuItem);

        mainMenuBar.add(staffMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addOUMenuItem;
    private javax.swing.JMenuItem addUserMenuItem;
    private javax.swing.JComboBox<String> assetTypeComboBox;
    private javax.swing.JPanel avBuyPanel;
    private javax.swing.JPanel avSellPanel;
    private javax.swing.JTabbedPane avaialbleTabbedPane;
    private javax.swing.JPanel availableOrdersPanel;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton buyBtn;
    private javax.swing.JButton buyRemoveBtn;
    private javax.swing.JComboBox<String> buySellComboBox;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel createLabel;
    private javax.swing.JPanel createOrdersPanel;
    private javax.swing.JPanel currBuyPanel;
    private javax.swing.JPanel currSellPanel;
    private javax.swing.JPanel currentOrdersPanel;
    private javax.swing.JTabbedPane currentTabbedPane;
    private javax.swing.JMenuItem deleteOUMenuItem;
    private javax.swing.JMenuItem deleteUserMenuItem;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JTextField qtyTextField;
    private javax.swing.JButton sellBtn;
    private javax.swing.JButton sellRemoveBtn;
    private javax.swing.JMenu settingsMenu;
    private javax.swing.JMenu staffMenu;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration//GEN-END:variables
}
