package userInterface;


public class userPage extends javax.swing.JFrame {

    /**
     * Creates new form staffInterface
     */
    public userPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        createNewOfferPanel = new javax.swing.JPanel();
        assetTypeComboBox = new javax.swing.JComboBox<>();
        orderTypeComboBox = new javax.swing.JComboBox<>();
        enterOrderNameLabel = new javax.swing.JLabel();
        enterOrderNameTextField = new javax.swing.JTextField();
        enterOrderQtyLabel = new javax.swing.JLabel();
        enterOrderQtyTextField = new javax.swing.JTextField();
        enterPriceLabel = new javax.swing.JLabel();
        enterPriceTextField = new javax.swing.JTextField();
        createOrderButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        graphPanel = new javax.swing.JPanel();
        currentOrdersTabbedPane = new javax.swing.JTabbedPane();
        currentBuyOrdersPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        currentBuyList = new javax.swing.JList<>();
        viewButton3 = new javax.swing.JButton();
        currentSellOrdersPanel = new javax.swing.JPanel();
        viewButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        currentSellList = new javax.swing.JList<>();
        availableOrdersTabbedPane = new javax.swing.JTabbedPane();
        sellOrdersPanel = new javax.swing.JPanel();
        viewButton1 = new javax.swing.JButton();
        deleteButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        sellOrdersList = new javax.swing.JList<>();
        buyOrdersPanel = new javax.swing.JPanel();
        viewButton2 = new javax.swing.JButton();
        deleteButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        buyOrdersList = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        settingsMenuBar = new javax.swing.JMenu();
        logoutMenuItem = new javax.swing.JMenuItem();
        staffMenuBar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Organisational Unit - STAFF");
        setPreferredSize(new java.awt.Dimension(820, 835));
        setResizable(false);

        createNewOfferPanel.setBackground(new java.awt.Color(255, 255, 255));
        createNewOfferPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Create New Offer", 0, 0, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        createNewOfferPanel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createNewOfferPanel.setPreferredSize(new java.awt.Dimension(0, 395));

        assetTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asset Type 1", "Asset Type 2", "Asset Type 3", "Asset Type 4" }));

        orderTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buy", "Sell" }));

        enterOrderNameLabel.setText("Enter Order Name:");

        enterOrderNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterOrderNameTextFieldActionPerformed(evt);
            }
        });

        enterOrderQtyLabel.setText("Enter Order Quantity:");

        enterPriceLabel.setText("Enter Price:");

        createOrderButton.setText("Create Order");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Create a new offer below:");

        javax.swing.GroupLayout createNewOfferPanelLayout = new javax.swing.GroupLayout(createNewOfferPanel);
        createNewOfferPanel.setLayout(createNewOfferPanelLayout);
        createNewOfferPanelLayout.setHorizontalGroup(
                createNewOfferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createNewOfferPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(orderTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154))
                        .addGroup(createNewOfferPanelLayout.createSequentialGroup()
                                .addGroup(createNewOfferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(createNewOfferPanelLayout.createSequentialGroup()
                                                .addGroup(createNewOfferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(createNewOfferPanelLayout.createSequentialGroup()
                                                                .addGap(66, 66, 66)
                                                                .addComponent(enterPriceLabel))
                                                        .addComponent(enterOrderQtyLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(enterOrderNameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(18, 18, 18)
                                                .addGroup(createNewOfferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(createOrderButton)
                                                        .addGroup(createNewOfferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(enterOrderQtyTextField)
                                                                .addComponent(enterOrderNameTextField)
                                                                .addComponent(enterPriceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                                        .addComponent(assetTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(createNewOfferPanelLayout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addComponent(jLabel1)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createNewOfferPanelLayout.setVerticalGroup(
                createNewOfferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(createNewOfferPanelLayout.createSequentialGroup()
                                .addContainerGap(65, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(assetTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(orderTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(createNewOfferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(enterOrderNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(enterOrderNameLabel))
                                .addGap(18, 18, 18)
                                .addGroup(createNewOfferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(enterOrderQtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(enterOrderQtyLabel))
                                .addGap(18, 18, 18)
                                .addGroup(createNewOfferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(enterPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(enterPriceLabel))
                                .addGap(18, 18, 18)
                                .addComponent(createOrderButton)
                                .addGap(19, 19, 19))
        );

        graphPanel.setBackground(new java.awt.Color(255, 255, 255));
        graphPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Graph", 0, 0, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        graphPanel.setLayout(new java.awt.BorderLayout());

        currentOrdersTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        currentOrdersTabbedPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        currentOrdersTabbedPane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        currentBuyOrdersPanel.setBackground(new java.awt.Color(255, 255, 255));
        currentBuyOrdersPanel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        currentBuyList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Your Buy Order 1", "Your Buy Order 2", "Your Buy Order 3", "Your Buy Order 4", "Your Buy Order 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(currentBuyList);

        viewButton3.setText("View");

        javax.swing.GroupLayout currentBuyOrdersPanelLayout = new javax.swing.GroupLayout(currentBuyOrdersPanel);
        currentBuyOrdersPanel.setLayout(currentBuyOrdersPanelLayout);
        currentBuyOrdersPanelLayout.setHorizontalGroup(
                currentBuyOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currentBuyOrdersPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)
                                .addGap(0, 0, 0))
                        .addGroup(currentBuyOrdersPanelLayout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(viewButton3)
                                .addContainerGap(194, Short.MAX_VALUE))
        );
        currentBuyOrdersPanelLayout.setVerticalGroup(
                currentBuyOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(currentBuyOrdersPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(viewButton3)
                                .addGap(0, 8, Short.MAX_VALUE))
        );

        currentOrdersTabbedPane.addTab("Your Current Buy Orders", currentBuyOrdersPanel);

        currentSellOrdersPanel.setBackground(new java.awt.Color(255, 255, 255));

        viewButton4.setText("View");

        currentSellList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Your Sell Order 1", "Your Sell Order 2", "Your Sell Order 3", "Your Sell Order 4", "Your Sell Order 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(currentSellList);

        javax.swing.GroupLayout currentSellOrdersPanelLayout = new javax.swing.GroupLayout(currentSellOrdersPanel);
        currentSellOrdersPanel.setLayout(currentSellOrdersPanelLayout);
        currentSellOrdersPanelLayout.setHorizontalGroup(
                currentSellOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(currentSellOrdersPanelLayout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(viewButton4)
                                .addContainerGap(194, Short.MAX_VALUE))
                        .addGroup(currentSellOrdersPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2)
                                .addContainerGap())
        );
        currentSellOrdersPanelLayout.setVerticalGroup(
                currentSellOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currentSellOrdersPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(viewButton4)
                                .addGap(8, 8, 8))
        );

        currentOrdersTabbedPane.addTab("Your Current Sell Orders", currentSellOrdersPanel);

        availableOrdersTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        availableOrdersTabbedPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        availableOrdersTabbedPane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        sellOrdersPanel.setBackground(new java.awt.Color(255, 255, 255));

        viewButton1.setText("View");
        viewButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButton1ActionPerformed(evt);
            }
        });

        deleteButton1.setText("delete");

        sellOrdersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Sell Order 1", "Sell Order 2", "Sell Order 3", "Sell Order 4", "Sell Order 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(sellOrdersList);

        javax.swing.GroupLayout sellOrdersPanelLayout = new javax.swing.GroupLayout(sellOrdersPanel);
        sellOrdersPanel.setLayout(sellOrdersPanelLayout);
        sellOrdersPanelLayout.setHorizontalGroup(
                sellOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sellOrdersPanelLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(viewButton1)
                                .addGap(43, 43, 43)
                                .addComponent(deleteButton1)
                                .addContainerGap(116, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sellOrdersPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane4)
                                .addContainerGap())
        );
        sellOrdersPanelLayout.setVerticalGroup(
                sellOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sellOrdersPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(sellOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(viewButton1)
                                        .addComponent(deleteButton1))
                                .addContainerGap())
        );

        availableOrdersTabbedPane.addTab("Available Sell Orders", sellOrdersPanel);
        sellOrdersPanel.getAccessibleContext().setAccessibleName("");

        buyOrdersPanel.setBackground(new java.awt.Color(255, 255, 255));

        viewButton2.setText("View");
        viewButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButton2ActionPerformed(evt);
            }
        });

        deleteButton2.setText("delete");

        buyOrdersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Buy Order 1", "Buy Order 2", "Buy Order 3", "Buy Order 4", "Buy Order 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(buyOrdersList);

        javax.swing.GroupLayout buyOrdersPanelLayout = new javax.swing.GroupLayout(buyOrdersPanel);
        buyOrdersPanel.setLayout(buyOrdersPanelLayout);
        buyOrdersPanelLayout.setHorizontalGroup(
                buyOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(buyOrdersPanelLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(viewButton2)
                                .addGap(43, 43, 43)
                                .addComponent(deleteButton2)
                                .addContainerGap(116, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buyOrdersPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3)
                                .addContainerGap())
        );
        buyOrdersPanelLayout.setVerticalGroup(
                buyOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buyOrdersPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(buyOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(viewButton2)
                                        .addComponent(deleteButton2))
                                .addContainerGap())
        );

        availableOrdersTabbedPane.addTab("Available Buy Orders", buyOrdersPanel);

        settingsMenuBar.setText("Settings");

        logoutMenuItem.setText("logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        settingsMenuBar.add(logoutMenuItem);

        jMenuBar1.add(settingsMenuBar);

        staffMenuBar.setText("Staff");
        jMenuBar1.add(staffMenuBar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(createNewOfferPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                        .addComponent(availableOrdersTabbedPane))
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(currentOrdersTabbedPane))
                                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(currentOrdersTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(availableOrdersTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(createNewOfferPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)))
        );

        availableOrdersTabbedPane.getAccessibleContext().setAccessibleName("Available Buy Orders");
        availableOrdersTabbedPane.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>

    private void viewButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void viewButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void enterOrderNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JComboBox<String> assetTypeComboBox;
    private javax.swing.JTabbedPane availableOrdersTabbedPane;
    private javax.swing.JList<String> buyOrdersList;
    private javax.swing.JPanel buyOrdersPanel;
    private javax.swing.JPanel createNewOfferPanel;
    private javax.swing.JButton createOrderButton;
    private javax.swing.JList<String> currentBuyList;
    private javax.swing.JPanel currentBuyOrdersPanel;
    private javax.swing.JTabbedPane currentOrdersTabbedPane;
    private javax.swing.JList<String> currentSellList;
    private javax.swing.JPanel currentSellOrdersPanel;
    private javax.swing.JButton deleteButton1;
    private javax.swing.JButton deleteButton2;
    private javax.swing.JLabel enterOrderNameLabel;
    private javax.swing.JTextField enterOrderNameTextField;
    private javax.swing.JLabel enterOrderQtyLabel;
    private javax.swing.JTextField enterOrderQtyTextField;
    private javax.swing.JLabel enterPriceLabel;
    private javax.swing.JTextField enterPriceTextField;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JComboBox<String> orderTypeComboBox;
    private javax.swing.JList<String> sellOrdersList;
    private javax.swing.JPanel sellOrdersPanel;
    private javax.swing.JMenu settingsMenuBar;
    private javax.swing.JMenu staffMenuBar;
    private javax.swing.JButton viewButton1;
    private javax.swing.JButton viewButton2;
    private javax.swing.JButton viewButton3;
    private javax.swing.JButton viewButton4;
    // End of variables declaration
}
